# .github/workflows/deploy-strato.yml
name: Deploy SSH STRATO
on: { push: { branches: [ main ] } }
concurrency: { group: deploy-strato-main, cancel-in-progress: true }

jobs:
  deploy:
    runs-on: ubuntu-22.04
    strategy: { matrix: { node-version: [22.16.0] } }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PNPM
        uses: pnpm/action-setup@v4
        with: { version: 10.12.1 }

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build (Vite base must match '/alisma/')
        env:
          VITE_EMAILJS_PUBLIC_KEY: ${{ vars.VITE_EMAILJS_PUBLIC_KEY }}
          VITE_EMAILJS_SERVICE_ID: ${{ vars.VITE_EMAILJS_SERVICE_ID }}
          VITE_EMAILJS_TEMPLATE_ID: ${{ vars.VITE_EMAILJS_TEMPLATE_ID }}
        run: pnpm build

      # Optional: SPA rewrite + cache-busting markers
      - name: Write .htaccess & markers
        run: |
          cat > dist/.htaccess <<'HTACC'
          <IfModule mod_dir.c>DirectoryIndex index.html</IfModule>
          <IfModule mod_rewrite.c>
            RewriteEngine On
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteRule ^ index.html [L]
          </IfModule>
          HTACC
          echo "$GITHUB_SHA" > dist/__build_id.txt
          sha256sum dist/index.html | awk '{print $1}' > dist/__index_sha256.txt

      # Optional: root redirect -> /alisma/ (keeps apex working)
      - name: Create root redirect index.html
        run: |
          mkdir -p redirect-root
          cat > redirect-root/index.html <<'HTML'
          <!doctype html><meta http-equiv="refresh" content="0; url=/alisma/">
          <script>location.href="/alisma/"</script>
          HTML

      - name: Install lftp
        run: |
          sudo apt-get -yq update && sudo apt-get -yq install lftp

      - name: Pre-deploy list (/alisma)
        env:
          H: ${{ secrets.STRATO_SSH_HOST }}
          U: ${{ secrets.STRATO_SSH_USER }}
          P: ${{ secrets.STRATO_SSH_PASS }}
        run: |
          lftp -u "$U","$P" sftp://$H -e "set cmd:fail-exit yes; set sftp:auto-confirm yes; cls -al /alisma || echo 'no /alisma yet'; bye"

      - name: Deploy app to /alisma
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.STRATO_SSH_HOST }}
          port: 22
          user: ${{ secrets.STRATO_SSH_USER }}
          pass: ${{ secrets.STRATO_SSH_PASS }}
          onlyNewer: false
          settings: 'sftp:auto-confirm=yes; net:timeout=8; net:max-retries=1; cmd:fail-exit=yes'
          localDir: 'dist/'
          remoteDir: '/alisma'
          reverse: true
          options: '--delete --verbose --ignore-time --overwrite --exclude-glob temp --exclude-glob temp/**'

      - name: Deploy root redirect (so https://alisma.at/ works)
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.STRATO_SSH_HOST }}
          port: 22
          user: ${{ secrets.STRATO_SSH_USER }}
          pass: ${{ secrets.STRATO_SSH_PASS }}
          onlyNewer: false
          settings: 'sftp:auto-confirm=yes; net:timeout=8; net:max-retries=1; cmd:fail-exit=yes'
          localDir: 'redirect-root/'
          remoteDir: '/'
          reverse: true
          options: '--verbose --ignore-time --overwrite --exclude-glob temp --exclude-glob temp/**'

      - name: Post-deploy list (/alisma)
        env:  
          H: ${{ secrets.STRATO_SSH_HOST }} 
          U: ${{ secrets.STRATO_SSH_USER }} 
          P: ${{ secrets.STRATO_SSH_PASS }} 
        run: |
          lftp -u "$U","$P" sftp://$H -e "set cmd:fail-exit yes; set sftp:auto-confirm yes; cls -al /alisma; bye"

      - name: HTTP check
        run: |
          set -e
          echo "Apex build id:";  curl -fsS https://alisma.at/__build_id.txt || true
          echo "/alisma build id:"; curl -fsS https://alisma.at/alisma/__build_id.txt | head -c 12 && echo
